//
//  SimplifiedBoundariesTests.swift
//  WandovaTests
//
//  Invariants of the bundled simplified border file
//  (world_countries_simplified.geojson, generated by
//  tools/simplify-borders.sh) relative to the full-resolution source.
//  If regeneration ever breaks one of these, the map either loses
//  countries, loses holes, or loses its performance headroom.
//

import XCTest
import MapKit
@testable import Wandova

final class SimplifiedBoundariesTests: XCTestCase {

    private var fullRes: [String: [MKOverlay]]!
    private var simplified: [String: [MKOverlay]]!

    override func setUp() {
        super.setUp()
        fullRes = CountryBoundaryService.shared.getCountryOverlays()
        simplified = CountryBoundaryService.shared.getRenderOverlays()
    }

    func test_simplifiedFile_coversSameCountriesAsFullResolution() {
        XCTAssertFalse(fullRes.isEmpty)
        XCTAssertEqual(
            Set(simplified.keys), Set(fullRes.keys),
            "Simplification must not add or drop any country (keep-shapes should preserve small islands and microstates)"
        )
    }

    func test_simplifiedGeometry_isSubstantiallySmaller() {
        let fullTotal = totalVertexCount(of: fullRes)
        let simplifiedTotal = totalVertexCount(of: simplified)

        // Full res is ~548K vertices, simplified ~44K (8%). The 20% bound
        // leaves room for retuning INTERVAL without silently regressing to
        // near-full-resolution rendering.
        XCTAssertGreaterThan(fullTotal, 400_000, "full-resolution file changed unexpectedly")
        XCTAssertLessThan(
            Double(simplifiedTotal), Double(fullTotal) * 0.2,
            "simplified file is too detailed (\(simplifiedTotal) of \(fullTotal) vertices) — was it regenerated without simplification?"
        )

        // The worst offender specifically: Canada is 68K vertices at full res.
        let canada = totalVertexCount(of: ["CA": simplified["CA"] ?? []])
        XCTAssertLessThan(canada, 10_000, "Canada should render with a few thousand vertices, got \(canada)")
    }

    func test_hitTestingKeepsFullResolution() {
        let fullUS = totalVertexCount(of: ["US": fullRes["US"] ?? []])
        let simplifiedUS = totalVertexCount(of: ["US": simplified["US"] ?? []])
        XCTAssertGreaterThan(fullUS, simplifiedUS * 5,
            "getCountryOverlays() (tap hit-testing) must keep serving full-resolution geometry")
    }

    func test_southAfrica_keepsLesothoHole() {
        let lesotho = CLLocationCoordinate2D(latitude: -29.61, longitude: 28.23)

        let interiorRings = allPolygons(in: simplified["ZA"] ?? [])
            .compactMap { $0.interiorPolygons }
            .flatMap { $0 }
        XCTAssertFalse(interiorRings.isEmpty, "South Africa lost its interior ring(s) in simplification")

        XCTAssertTrue(
            interiorRings.contains { ring(of: $0).contains(point: lesotho) },
            "No South Africa interior ring contains Lesotho's centroid — the hole moved or collapsed"
        )
    }

    // MARK: - Helpers

    private func allPolygons(in overlays: [MKOverlay]) -> [MKPolygon] {
        overlays.flatMap { overlay -> [MKPolygon] in
            if let polygon = overlay as? MKPolygon { return [polygon] }
            if let multi = overlay as? MKMultiPolygon { return multi.polygons }
            return []
        }
    }

    private func totalVertexCount(of overlaysByCountry: [String: [MKOverlay]]) -> Int {
        overlaysByCountry.values.flatMap(allPolygons(in:)).reduce(0) { $0 + vertexCount(of: $1) }
    }

    private func vertexCount(of polygon: MKPolygon) -> Int {
        polygon.pointCount + (polygon.interiorPolygons ?? []).reduce(0) { $0 + vertexCount(of: $1) }
    }

    private func ring(of polygon: MKPolygon) -> [CLLocationCoordinate2D] {
        var coords = [CLLocationCoordinate2D](repeating: CLLocationCoordinate2D(), count: polygon.pointCount)
        polygon.getCoordinates(&coords, range: NSRange(location: 0, length: polygon.pointCount))
        return coords
    }
}

private extension Array where Element == CLLocationCoordinate2D {
    /// Ray-casting point-in-ring test in plain lat/lon space; fine for a
    /// ring nowhere near the antimeridian.
    func contains(point: CLLocationCoordinate2D) -> Bool {
        guard count > 2 else { return false }
        var inside = false
        var j = count - 1
        for i in 0..<count {
            let a = self[i], b = self[j]
            if (a.latitude > point.latitude) != (b.latitude > point.latitude),
               point.longitude < (b.longitude - a.longitude) * (point.latitude - a.latitude)
                   / (b.latitude - a.latitude) + a.longitude {
                inside.toggle()
            }
            j = i
        }
        return inside
    }
}
